### ISSUE TITLE
How do I add this repository?

### ISSUE THREAD

**Issue by latinvm** [pfunkmallone/HACS-camect-integration#3]
Whenever I try to add this repo all I see is:

![image](https://user-images.githubusercontent.com/7670602/93482763-58999d80-f900-11ea-8411-ea462eed04ae.png)
I can't select a type, after adding I don't see any camect add-ons in the store either.

Thanks

**Comment by pfunkmallone** [comment]
This repo is part of the default HACs repositories. Once you have a recent version of HACS installed (the image you posted looks like an older version), you can simply click the "+" symbol in the bottom right of your Home Assistant HACS interface, search for the keyword Camect, and the integration and card should be there. This gif shows the card, but the integration is the same process.
![ezgif com-resize](https://user-images.githubusercontent.com/51976218/93537662-c69a9080-f911-11ea-9b3c-73de137850b6.gif)
